REVOKE ALL ON SEQUENCE "ai"."outbox_id_seq" FROM ai_worker;
REVOKE ALL ON TABLE "ai"."outbox" FROM ai_worker;
REVOKE ALL ON TABLE "ai"."processing_job_dlq" FROM ai_worker;
REVOKE ALL ON TABLE "ai"."chunks" FROM ai_worker;
REVOKE ALL ON TABLE "ai"."processing_jobs" FROM ai_worker;
REVOKE ALL ON SCHEMA "ai" FROM ai_worker;
REVOKE ALL ON TABLE "course"."documents" FROM ai_worker;
REVOKE ALL ON TABLE "course"."outbox" FROM ai_worker;
REVOKE ALL ON SCHEMA "course" FROM ai_worker;
DROP ROLE IF EXISTS ai_worker;
