export enum SuperAdminBootstrapMode {
  FIRST_BOOTSTRAP = 'FIRST_BOOTSTRAP',
  LOCKOUT_RECOVERY = 'LOCKOUT_RECOVERY',
  NORMAL = 'NORMAL',
  QUORUM_RECOVERY = 'QUORUM_RECOVERY',
  SEED_SECOND = 'SEED_SECOND',
  UNAVAILABLE = 'UNAVAILABLE',
}
