---
- name: Restart K3s after configuration change
  ansible.builtin.systemd:
    name: k3s.service
    state: restarted
  when:
    - not (k3s_install_required | bool)
    - not ansible_check_mode

- name: Validate Nginx configuration
  ansible.builtin.command:
    cmd: nginx -t
  changed_when: false

- name: Reload Nginx edge
  ansible.builtin.systemd:
    name: '{{ nginx_service_name }}'
    state: reloaded
